### ISSUE TITLE
Tar- ("Failed to extract tarball")

### ISSUE THREAD

**Issue by lucaspanayiotou** [OasisLMF/OasisLMF#177] opened 2019-02-01 16:43 UTC
Hi we occasionally run into the following error.
Seems to trip when using large files, or chaining a high amount of small analysis together.

Have investigated with B Hayes.

Issue occurs in flamingo_utils

def extract_tarball(tar_file, output_dir):
   unzip_command = "tar xf {} -C {}".format(tar_file, output_dir)
   unzip_result = subprocess.call(unzip_command, shell=True)
   if int(unzip_result) != 0:
       logging.getLogger().debug(
           "unzip command: {}".format(unzip_command))
raise Exception("Failed to extract tarball")

**Comment by sr-murthy** [comment] 2019-02-01 17:23
The first step is to reproduce the problem on the same or similar instance - if file size is the problem that causes the `tar` command to fail then try running the `tar` command directly on the file. If it breaks then perhaps the code can be amended to detect large tar files (above a certain limit) and to split these into chunks (using `split`), extract the chunks and then reassemble them (using `cat`).

**Comment by lucaspanayiotou** [comment] 2019-02-01 17:53
Hi, i should mention we have tried the above step.  we have also tried concurrently tarring a large set of files while untarring the same set of files to see if there was some resource constraint.

with the above we could not reproduce the error.

Ben mentioned that Mark has perhaps rectified this error before, but only when tarring files as opposed to untarring.

On 1 Feb 2019 17:23, S Murthy <notifications@github.com> wrote:

The first step is to reproduce the problem on the same or similar instance - if file size is the problem that causes the tar command to fail then try running the tar command directly on the file. If it breaks then perhaps the code can be amended to detect large tar files (above a certain limit) and to split these into chunks (using split), extract the chunks and then reassemble them (using cat).

**Comment by mpinkerton-oasis** [comment] 2019-02-04 16:03
I just checked, and the fix that went in for the tarfile creation is unrelated.

Does it fail consistently for particular analyses? With nothing else to go on, we could retry the extraction a couple of times in the code before failing.

**Comment by mpinkerton-oasis** [comment] 2019-02-04 16:07
A more advanced approach would be to put a queue around this, so we have more control over this.

**Comment by honlau** [comment] 2019-03-12 09:43
Related to https://github.com/OasisLMF/OasisPlatform/issues/34 unfortunately, I'm still seeing the tarball errors occurring.
Can you please implement some error handling into this process as it is currently failing at what should be the easiest step?
A "tar -tvf filename.tar.gz" command will verify the integrity of a tarball prior to transferring it from the worker to the mid tier.  The file should be deleted and re-tarred if it fails this integrity check (up to 2 times).
This tends to happen in periods of high activity and with large output file sizes (1gb+).

**Comment by honlau** [comment] 2019-03-12 13:45
Alternatively, if say we could set an environment variable that disables the tarring part of the process and just straight transfers the output files over that would be useful.

**Comment by mpinkerton-oasis** [comment] 2019-03-12 14:44
I thought you were looking into changes with your filesystem mounting to address this. Has that been done? Does it not work? A retry could still make sense, but I would have expected tarring to be quite robust in general.

**Comment by honlau** [comment] 2019-03-12 16:36
The change to the mount was performed and I'm still seeing this error. It's not manifested in the UAT or Prod environment since the change (fingers crossed), so it's hard to narrow down the issue to anything else.  I'm running a single server setup where everything is running from one machine, so this may have some impact, but I agree that tarring should be a fairly robust process (I've never been able to replicate this directly in Linux).  However, as a more lateral solution, I've started a conversation with Ben H about cutting out the moving output files step entirely by creating the outputs in a shared location that both the worker and mid tier can access.

**Comment by mpinkerton-oasis** [comment] 2019-03-12 16:48
That has essentially already happened in the new API architecture, as there is no intermediate file storage in a "mid-tier".

**Comment by mpinkerton-oasis** [comment] 2019-03-13 11:36
It might also be worth adding a standalone script that cycles the same Python code for some large files. Th en you can vary the file size, concurrency etc and see exactly when the issues occurs, rather than waiting for it to occasionally happen.

**Comment by honlau** [comment] 2019-03-29 13:30
Were there actually any changes made on the Oasis side to fix/alleviate this?  I'm still seeing this exclusively when running ARA, who have their slightly different worker...

**Comment by mpinkerton-oasis** [comment] 2019-08-20 10:34
@lucaspanayiotou @honlau can this be closed now?

**Comment by lucaspanayiotou** [comment] 2019-08-20 10:47
If i recall, we made a change to the mount config in /etc/fstab which disabled buffering, or something along those lines.

Seems to be fixed. Ok to close.

**Closed** 2019-08-20 11:12 UTC
