### ISSUE TITLE
Lookup area peril column

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#302] opened 2019-06-05 15:00 UTC
If you set "peril_area_id_col" to a value other than "AREA_PERIL_ID", with other settings updated accordingly, then you don't get the area peril set in the keys response.

**Comment by sr-murthy** [comment] 2019-06-05 15:46
This is not a bug - this field is purely informational.

**Comment by sr-murthy** [comment] 2019-06-05 16:21
Closing - as I said above this field is not really meant to be customised. If we did it would mean adding some unnecessary complexity to the keys file writing method in the lookup factory, which expects the lookup to set AP IDs using a key named `area_peril_id`.

https://github.com/OasisLMF/OasisLMF/blob/develop/oasislmf/model_preparation/lookup.py#L381

**Closed by sr-murthy** 2019-06-05 16:21 UTC

**Comment by mpinkerton-oasis** [comment] 2019-06-05 16:30
@sr-murthy what is the point of the "peril_area_id_col" setting? Also, we should explicitly handle the case above better as the error is based on the area peril ending up as blank in the keyes reponse - the actual lookup runs without error.

**Comment by sr-murthy** [comment] 2019-06-05 16:49
The `peril_area_id_col` is used during the construction of the AP Rtree file index

https://github.com/OasisLMF/OasisLMF/blob/develop/oasislmf/utils/peril.py#L348

The built-in lookup doesn't process the AP source file directly - it process the Rtree file index created from the source file. In order to read the source file, the code has to know which columns represent what type of information. It is for this reason that there is a `peril_area_id_col` field. The file index creation is separate from the lookup process.

If you try changing the AP ID field name in the keys data to something other than `area_peril_id` - it will break.
